# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 496fe7ad929b5d67f6fdd9e28418cb0d4f404704fbadce99d015e4622a9fd31df8d12aa0e89547deea32038ba0499698e44bccf7a31cfa430b5ddd7a1670db59

test:
  secret_key_base: 1d0ea66fa04082d100e4c330db0bd748ee36b6b8d90fdce76028ea5f2c80df823c2a88bce2cab8e17a3fffe9d5854e86e1ca97dc9d25f6364810d6452b7b5981

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
